"""Commit everything from models.py

Revision ID: 1c2fa871bb2b
Revises: 
Create Date: 2023-06-30 02:23:11.060374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2fa871bb2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_table',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('nice_total_disk_usage', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('quota_percent', sa.Float(), nullable=True),
    sa.Column('total_disk_usage', sa.Float(), nullable=False),
    sa.Column('purged', sa.Boolean(), nullable=False),
    sa.Column('quota', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('history_table',
    sa.Column('hid', sa.Integer(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('hid')
    )
    op.create_table('notification_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=256), nullable=False),
    sa.Column('message_id', sa.String(length=256), nullable=True),
    sa.Column('sent', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=256), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['message_table.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history_notification_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_id', sa.String(length=256), nullable=False),
    sa.Column('h_date', sa.DateTime(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['history_table.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['notification_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_notification_table')
    op.drop_table('notification_table')
    op.drop_table('history_table')
    op.drop_table('user_table')
    op.drop_table('message_table')
    # ### end Alembic commands ###
